<section>

    <h1>L'univers des livres et magazines - <?= Library::$totalItems ?> en stocks</h1>
    <article>
        
        <div>
            <?= $book1->getTitle() ?>
        </div>
        <div>
            <?= $book1->getAuthor() ?>
        </div>
        <div>
            <?= $book1->getInfo() ?>
        </div>
       
    </article>

    <article>
        
        <div>
            <?= $magazine1->getTitle() ?>
        </div>
        <div>
            <?= $magazine1->getAuthor() ?>
        </div>
        <div>
            <?= $magazine1->getInfo() ?>
        </div>
    
    </article>

    <article>
        
        <div>
            <?= $book2->getTitle() ?>
        </div>
        <div>
            <?= $book2->getAuthor() ?>
        </div>
        <div>
            <?= $book2->getInfo() ?>
        </div>
    
    </article>

    <article>
        
        <div>
            <?= $magazine2->getTitle() ?>
        </div>
        <div>
            <?= $magazine2->getAuthor() ?>
        </div>
        <div>
            <?= $magazine2->getInfo() ?>
        </div>
    
    </article>

</section>