<section class = "container">

    <h1>L'univers des livres et magazines - <?= Library::$totalItems ?> en stocks</h1>
    <article>
        
        <div>
            <img src="assets/images/" alt="">
        </div>
        <div>
            <h3><?= $book1->getTitle() ?></h3>
        </div>
        <div>
            <p>Auteur : </p><?= $book1->getAuthor() ?>
        </div>
        <div>
            <p><?= $book1->getInfo() ?></p>
        </div>
       
    </article>

    <article>
        
        <div>
            <img src="assets/images/" alt="">
        </div>
        <div>
            <h3><?= $magazine1->getTitle() ?></h3>
        </div>
        <div>
            <p>Auteur :</p><?= $magazine1->getAuthor() ?>
        </div>
        <div>
            <p><?= $magazine1->getInfo() ?></p>
        </div>
    
    </article>

    <article>

        <div>
            <img src="assets/images/" alt="">
        </div>
        <div>
            <h3><?= $book2->getTitle() ?></h3>
        </div>
        <div>
            <p>Auteur : </p><?= $book2->getAuthor() ?>
        </div>
        <div>
            <p><?= $book2->getInfo() ?></p>
        </div>
    
    </article>

    <article>
        
        <div>
            <img src="assets/images/" alt="">
        </div>
        <div>
            <h3><?= $magazine2->getTitle() ?></h3>
        </div>
        <div>
            <p>Auteur :</p><?= $magazine2->getAuthor() ?>
        </div>
        <div>
            <p><?= $magazine2->getInfo() ?></p>
        </div>
    
    </article>

</section>